#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003
server:
  max-http-header-size: 20480

spring:
  application:
    name: product-data-service
  zipkin:
    base-url: http://localhost:9411

#上下文
#server:
#  servlet:
#    context-path: /
#    context-path: /sc-product-api


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
